apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: query-private
spec:
  selector:
    matchLabels:
      name: query
      version: v1
      ring: private
  replicas: 1
  template:
    metadata:
      labels:
        name: query
        version: v1
        ring: private
    spec:
      containers:
      - name: query
        image: migolfi.azurecr.io/ringleader
        ports:
        - containerPort: 8080
        env:
          - name: RING
            value: private
      imagePullSecrets:
        - name: azurecr
---
apiVersion: rings.microsoft.com/v1alpha1
kind: Ring
metadata:
  name: query-v1-private
spec:
  # Deploy to environment
  deploy: true
  # Custom Claims
  claim: private
  entryPoints:
    # Source of traffic (eg: 80 or 443)
    - http
    - https
    - internal
  match: PathPrefix(`/query/v1`) && Headers(`x-ring`, `private`)
  selector:
  # Target deployment instances
    # name of microservice
    name: query
    # Major version of microservice
    version: v1
    # Branch name
    ring: private